missing functional header
/mnt/d/dev/Field-Map-Editor/linux/build/RelWithDebInfo/_deps/openviii_cpp_wip_fetch-src/src/open_viii/archive/Archives.hpp:1112:19: note: ‘std::invoke’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
/mnt/d/dev/Field-Map-Editor/linux/build/RelWithDebInfo/_deps/openviii_cpp_wip_fetch-src/src/open_viii/archive/Archives.hpp: In member function ‘open_viii::archive::ArchivesIteratorVisitor::MyVariantClass<Func>::return_val_t open_viii::archive::ArchivesIteratorVisitor::MyVariantClass<Func>::operator()(open_viii::archive::Archives::FIFLFSRef2) const requires  invocable<Func, open_viii::archive::FIFLFS<false>&>’:
/mnt/d/dev/Field-Map-Editor/linux/build/RelWithDebInfo/_deps/openviii_cpp_wip_fetch-src/src/open_viii/archive/Archives.hpp:1124:19: error: ‘invoke’ is not a member of ‘std’
 1124 |       return std::invoke(m_function.get(), fiflfs);
      |                   ^~~~~~