missing cstdint header
/mnt/d/dev/Field-Map-Editor/linux/build/RelWithDebInfo/_deps/openviii_cpp_wip_fetch-src/src/open_viii/graphics/BPPT.hpp:165:18: error: ‘uint8_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
  165 |   constexpr std::uint8_t
      |                  ^~~~~~~